export default [
  "天天鸟白島（乐,又没有天天玩",
  "dependabot都比chihuo氵的勤快",
  "chihuo两周没水了",
  "猫猫：玩mc",
  "看我带头水一个commit",
  "还是ys好玩，特别是B服，下载也简单",
  "chihuo自己说说上次玩mc是什么时候",
  "现在叫的开心，到时候就是天天ys",
  "两周，哦，最近水过的人就别来灵丹妙药了",
  "不如看看gh文档",
  "你给我个request和response示例，然后解释下request的参数哪里来",
  "chihuo坏掉了，拖出去吧",
  "谁要写js啊",
  "你这个猫猫，它是老虎吗",
  "你一个会js的人，怎么不去写点js呢",
  "star大师mzw",
  "lzy:其实我特别会git，我是先diff再squash所有更改到一个commit里面，所以你们会觉得我是手动改的（x",
  "建议直接转给sci，sci自己关一会，实惠又划算",
  "封chihuo不是误封，早该封封了（x",
  "三格四格我哪里知道多少",
  "dependabot能进我邮箱，但是chihuo不行",
  "chihuo:我这有好康的要不要跑",
  "连接mzw qq，检测到chihuo发送ys后自动回复今天chihuo contribute了吗",
  "撅chihuo就行（x",
  "谁写个fail2ab，反打chihuo",
  "自用不难，代码留给读者作为回家作业",
  "每日一问：今天的ys还是一样好玩吗",
  "每日一问：chihuo的评论修了吗",
  "chihuo你好闲啊（x",
  "chihuo,assign我干嘛",
  "chihuo最喜欢assign别人然后自己玩ys了",
  "喝了一下chihuo柠檬水，这是加了多少柠檬（和自己泡的不太一样",
  "猫猫没学上了（x，想去上的都上不了了，生活不易猫猫哭泣）",
  "领先时代bbg",
  "win:盘不好怪我？",
  "什么个位数小项目（x",
  "这是装Ubuntu的时候既没选国内镜像又没装解码器，Ubuntu极致体验（x",
  "快进到使用无障碍，要什么显示器，还是要注意一下（）",
  "闭源还占gayhub资源，屑",
  "哦那个免费的商业项目 还没看过（",
  "看别人写php都写die() 你们php好可怕（x",
  "“BBG托管服务是一个类似于wordpress.com的博客托管系统”",
  "?bbg-storage你们就写了个lzy needs 50$",
  "“Maybe I can have a try(x”",
  "如果早知道 bbg有那么好玩",
  "去打一下电动吧",
  "这个是阿伟为了不让阿嬷知道他偷学linux，所以故意伪装成xp",
  "我们出繁体是为了团结两岸三地",
  "我要是会就不会在node群中混入两个py了（",
  "猫猫感觉到大事不妙，一会就要被chihuo玩了（x",
  "我找了个去年的截图，你凑合一下，一会梦境会解锁完整内容",
  "你给chihuo刷礼物呢",
  "我来看看，到底是blame呢还是fix呢",
  "这两天都沉迷于github（）",
  "只有我NAS最低配了（）",
  "所以 服务于学生 你可以登吗（",
  "mzwing: steal(key)",
  "群友：*网站上线* 我：*burp启动*",
  "function let_friend_down(x",
  "telegra。ph/The-Usual-Lisp-04-30 晚点vw5r（",
  "都是抄的 我没写过网页（",
  "鸟白岛真好玩 是啊现在也在玩",
  "?人在鸟白岛",
  "我去鸟白岛了，git是很好玩的，可以多玩玩",
  "一会鸟白岛",
  "但是我在鸟白岛啊",
  "ys真好玩（x",
  "/mail dmca@github.com",
  "“今天没ab他”",
  "劝你多想想别的",
  "要水不能水过头，commit message都不好好写 又不是你自己的repo",
  "什么第三方小脚本（",
  "pnpm，什么小软件，dependabot都不支持",
  "让我改一下，你要pnpm还是yarn",
  "mzw!! 你在干什么啊啊 fix fix fix",
  "你希望重写吗 行，那我来吧 修了，你本地重新checkout远程",
  "没大事别故意merge，给我rebase",
  "我明天看，要是有问题你这commit就无了",
  "chihuo：水commit大成功",
  "都没用过，教给你们了（）",
  "只能我来帮你了（x 帮你改改，加点药进去",
  "有4个Secury问题<s>，Dismiss就行了，都是docsify不好</s>",
  "跨repo也可以merge的嘛，重写git history我觉得不好（）",
  "有xss吗，我来玩",
  "帮我重写下py，写不对就来blame你，正好你闲（x",
  "ys真好玩（x",
  "sci又水了个什么",
  "应该是我节点太去中心了，aws免费额度就够用了",
  "@sci 你在bbg根目录玩flash小游戏？",
  "什么咕咕咕小网站",
  "你peer下sci，就是去中心了（x 指sci根本连不上中心（x",
  "/ban chi",
  "什么chrome73",
  "你们ts没有 什么在什么数组里的条件表达式吗",
  "群猫猫增加了（",
  "我是baiyuanneko，我改好了",
  "我在issue里15天前说的办法",
  "你看，改成半个ng",
  "lang我还要rebase，submodule交给第三方小dependabot",
  "ubuntu速通",
  "您这两天在开riscv峰会吗，我这边有人做安全密钥（（",
  "哦，你觉得可以那你改一下",
  "要不要考虑装个git",
  "很好，我rebase",
  "@sci 你又偷偷用tab了是吧",
  "mcs也能改成轮询的，但是这样我就不能偷偷玩mc了（不是",
  "rss主要是用来提醒chihuo今天有没有contribute的（x",
  "我 是 学 生",
  "我氵个commit试试rss",
  "跑在你群最低性能机器上（",
  "chihuo连个maomaoquotes都不放出来",
  "lzy的bot就是好抄（x",
  "我是萌新啊（x",
  "自己的服连自己都不玩是吧",
  "lzy：你们怎么一晚上都在玩bot（x",
  "mc游玩许可是吧（x",
  "我们直接@chibot rm -rf /*",
  "chibot出来玩mc",
  "chibot去玩mc了",
  "问就是我这有个好康的 archlinux.org",
  "群nix可以出来传教了",
  "那我们就让pnpm人来改吧",
  "看来这是真的好玩",
  "别@ 睡觉了",
  "又不是你只丢个url",
  "总感觉你这个没什么用（",
  "收集群友语录闭源的屑",
  "chihuo写个前端对接下后端ab 付完款自动开始",
  "chihuo可以去搞黑产ab别人赚钱（x 毕竟，chihuo特别熟练",
  "优美ts",
  "我：这是身份证吗 哦你的身份证已经有了(x",
  "建议：第三方小镜像",
  "毕竟用了小脚本（",
  "@chihuo 然后就可以随时随地玩ys了",
  "chihuo:其实我很会linux，我一直在linux上玩ys，只是我假装只能在win上玩，显得我玩的比较少 好像也没有显得很少）",
  "等我切个号回复下（x",
  "看了下只是你没权限（x",
  "GPL开源不开全的屑",
  "我只是做个chihuoquotes的poc罢了 我随时能生成 为什么要记",
  "dll是不是sci的msf做出来的（",
  "没ms store（",
  "我装了个win server 2022,开学万一有软件不兼容就vm了（",
  "你看肯定是试过",
  "送我 我拿安卓换",
  "哦，那你买我的号就行 加上mc的钱就行",
  "我给chihuo丢个pgp加密（?",
  "小朋友你这个bbg写得不错啊",
  "群里直接开pgp 其他群友：*退群*",
  "明文放群里（x",
  "v2确实够厉害",
  "encode下，然后找个小网站公开密钥，就说测试新调制方法",
  "有，业余卫星，你直接用就是（x",
  "chibot哪有sprb好玩",
  "我们在涩涩（并没有",
  "哦，是时候/ban chihuo了", //matrix
  "赶紧问柏园猫猫要个Mod，然后就能滥权了", //matrix
  "chihuo能不能休息一下啊 天天玩bot，我只是希望你能好好念书", //matrix
  "不过群员能力每人可以写一个出来",
  "不清楚有没有上传量限制/不知道能不能涩涩", //matrix
  "哦确实，我大概是VIP（x", //matrix
  "electron里开网页：我是桌面应用啦", //matrix
  "等群友都成年我再给你们涩涩吧（x", //matrix
  "arch多好玩", //matrix
  "我的代码量（）百行都没（）", //matrix
  "因为别人开源了，而不像某人有某些原因", //matrix
  "给可怜的只能用公共pxy的猫猫用", //matrix
  "人大代表：我谢谢你，小伙子干的不错啊", //matrix
  "去了下gh，blame了一个pr", //matrix
  "linux上有猫猫（cat），它有头（head）也有尾（tail）", //matrix
  "鸟白岛，启动！", //matrix
  "这种令人血压高的我一般不看", //matrix
  "哦，晚点拿去NLP，造一个maomaobot", //matrix
  "只要我不用英语，你们就骗不到我", //matrix
  "为什么要写sort呢（x", //matrix
  "但是gh和matrix有什么关系呢（ 只是因为pro就红名？）", //matrix
  "没事，其实chihuo很会ctrl c ctrl v的",
  "tabnine：这人怎么写代码",
  "copilot：让我当机长算了",
  "嗯，following task是什么，我看不到",
  "建议用macOS去，有App Store 还可以给Apple打钱",
  "sci你又赚差价了，你说说你买进多少",
  "chihuo仙贝比较多，可以卖仙贝买Dev",
  "你捐赠个开发者帐号订阅出来 Apple的",
  "chihuo，谢谢你",
  "去年的我大概还能写（",
  "我现在没法测，除非你把你mac root ssh 给我（x",
  "@chihuo 那么有吗，没有",
  "之后我大概没空维护（",
  "开发？什么开发还要18岁才能开发",
  "看来是涩涩开发 开发一下群友（x",
  "dependabot今天偷懒了",
  "我最喜欢让别人RTFM了",
  "群里有个super ci，感觉比ghci好用",
  "？你还收录本子",
  "mc？mc好玩！",
  "@chihuo sci都没你那么喜欢（x",
  "群仙贝浓度终于可以下降了",
  "还以为你help是动态更新的，没想到是静态的",
  "chihuo在baiyuannekoshelp藏私货",
  "基于Arch一直偷AUR（",
  "要跨发行版嘛（ 那么 我们有没有建成  主义社会呢",
  "其实是给小py玩ai做准备（",
  "收你一年使用费我就不怒了（x",
  "这是全部数据库当然不开源 要开源也不会流向你的",
  "pgp最后还是会被gpg代替的（x",
  "全部数据，鸟白岛65次，ys 265次 sprb 11次 鳥白島15次",
  "ai就是要大的数据，哪怕数据不精",
  "精选对ai没用（）",
  "maomaoquotesall.txt 1852行",
  "总结大会（）",
  "鸟白岛 平假名片假名各一次",
  "还是太少了，输出乱码（",
  "bbg商业代码：*泄漏* 虽然是免费的商业计划（x",
  "有这时间不如去把开着的issue解决了",
  "怎么还有广告",
  "mac: 哼哼，",
  "scientificworld/homebrew-114514",
  "不考虑就发出来，屑",
  "chihuo去造个小猿搜题bot就行",
  "你们Apple就偷着乐吧，开发个App都要交钱", //matrix
  "element又不是chihuo写的，怎么会有xss呢", //matrix
  "群miku出来过生日",
  "For some reason,I am playing mc(x",
  "什么下载地址 这就给bot添加let me google that for you功能（x",
  "哦，四舍五入上大学了，您",
  "sci高考都不用了",
  "oh，你上大学了（？",
  "因为并没有人用/并没有人不让我用",
  "找我玩来上海就行（ 学校在临港",
  "您强强，来我这可惜了",
  "administrator@sxxu.edu.cn 我有edu邮箱了（x",
  "@柏园猫猫 贴贴",
  "我这个直接import的，我也不知道怎么处理的（x",
  "他怎么不说句话（",
  "哦，现在CHANGELOG没翻",
  "chihuo给so1ve送homo了吗",
  "什么登录百度账号",
  "sci去创一个仙贝社",
  "偷什么图（",
  "sci比较方便",
  "上海 中本贯通 计算机",
  "哦，那你pr就好了（x",
  "oi有什么好玩的，还是妹子可爱",
  "你不能 > 引用1 > 引用2 吗",
  "我觉得你这个手动筛选标准有点低（",
  "thanks for inventing JavaScript",
  "python人：c86是什么（x",
  "快进到天天特殊时期",
  "thx, I will review it later",
  "使用0行代码修复了此错误",
  "@zzjzxq33 你不要被感染啊（",
  "高性能bot在线率就是高",
  "挂服务器的是柏园猫猫（",
  "@柏园猫 这就是Win",
  "as soon as possible(x",
  "我直接import的 屑的只有chihuo",
  "建议你把dependency都重写一遍，顺便把js也重写一遍 这样大家就会感谢chihuo的js了",
  "chihuo又玩bot了，我玩mc去了",
  "<回复 猫猫今天contribute了吗> @chibot  contribute了，你呢",
  "感动猫猫（x",
  "其实chihuo是chibot调用器，只是chihuo一直假装自己是一个普通人",
  "你看插件源码，关键词随机匹配（",
  "你可以猜猜是byn ban你还是我ban你",
  "<sci:514=无意识>@sci 114=sci（x",
  "去年的我还能写  今年的我也写出来了）",
  "我真是太高性能了（x",
  "我 只 会 p y",
  "其实chihuo特别会是吧",
  "renpy to js",
  "你renpy哪不会 我可以让你RTFM",
  "chihuo会咕噜咕噜吗（",
  "其实打开nekopara就可以听我和柏园猫的咕噜咕噜了（x",
  "*香子兰的咕噜咕噜* 但是没录声音（",
  "<zzjzxq33:99+了>@zzjzxq33 chihuo负主要责任（x",
  "@chihuo 对了你们住校能玩ys吗（ 每日任务不做没事吗）",
  "还有就是(ys)B服没防沉迷吗（",
  "下一篇博文写 在NBFLS玩ys指北（x",
  "cur是什么（ Canonical User Repository",
  "哦，刚才只看到电子游戏",
  "全开了so1ve防火墙（x",
  "哦，刚才只看到电子游戏",
  "又没有人不给我玩（",
  "我这有个好东西一直等着你",
  "botpara",
  "@sci 这就是M2 你开qemu（x",
  "你自己下个镜像提取嘛",
  "但是chihuo有没有5r呢",
  "#sci把chihuo榨得一点也不剩了#",
  "你多的内容都是你自己在玩）",
  "<sci:谁告诉我icalingua要验证码然后就关了怎么办（> 1. 重开 2. 我练功发自真心",
  "每日chihuo✓",
  "chihuo浓度大于sci了",
  "mac人不一样吧（",
  "那你App Store 群友还特别喜欢",
  "有mbp mi notebook pro",
  "ydd：这个我会（x",
  "能本地的别走远程",
  "这就偷你剪贴板",
  "然而buff/cache都还没塞满",
  "有22G内存完全没用过（ 可用是46G）",
  "js写的有异常的话，直接不管（x",
  "你不是在玩mint吗（ 群全栈",
  "差点chihuo就要重写js了",
  "是因为chibot掉线了（ 所以显得概率高（x",
  "Recent Commits to blog-src:main add an article",
  "valine 一个都没实现（ 哦，应该是marked没实现）",
  "M2还kali 快来Artix",
  "算一下概率",
  "@chibot 上线",
  "你怎么还在configure",
  "视力好（x 然而并没有那么多空间给我放素材",
  "我是日语人啊（）",
  "高数和大英感觉要挂（x",
  "我DSM 60%是animation（",
  "@chibot crnmsl",
  "@chibot bdwpnmsl",
  "@chihuo 你不是说你have a try吗",
  "dependaBot's Blog Generator",
  "暂无需求（ 需求大了我直接去win（x",
  "装个nvidia studio driver",
  "可能是lzy拖延症强到传染给学校了",
  "你们不要flood我邮箱好吗 说点有用的",
  "哦，那我unsubscribe？",
  "我也fwd的",
  "那你弄个不间断电源",
  "乐，你就编译去吧（",
  "三天军训啊三天",
  "@sci 不是仙贝吗",
  "大概都这样（？",
  "明天试试obs吧（ 人死了",
  "裂开了，不止超星，军训还要开九个小时会议 国庆也要训",
  "mc里的我：autofish",
  "@mzw 哦，那会给lzy通知",
  "你可以发图（ 虽然我已经有一堆通知了",
  "你们要不要压一点代码，下个月PR参加Hacktoberfest（",
  "我觉得差不多",
  "@chihuo 工地英语",
  "mc里的我：autofish  钓了一晚上（",
  "vue-cli什么小软件，连pnpm都不支持 只是帮so1ve发的(x",
  "我进去人没了 难度还增加了",
  "心理医生：今天我来教大家写一个AI",
  "小模型，从欠拟合到过拟合",
  "<sci: bath完要穿衣服（x>  optional dependency (x",
  "sci那个放大化(mc服)其实很难玩（x",
  "写得好我当然有信心开源啊（",
  "<sci: 什么cv工程师> 也就参加点小比赛，队友都很摸鱼，但是可以蹭学校饭",
  "用核显还不如用CPU 不会的话建议某宝啥都有",
  "我担心你数据还是不够（）",
  "虽然我只玩过CV，不会您的NLP",
  "chiblog: *改名 chihuo的摸鱼小池*",
  "那你丢colab给google看去",
  "有显卡吗，没的话最终训练可以用我3070（x",
  "@chihuo 你说你两周能学会的，那就不急 一点点学就行",
  "@sci 其实是互惠，因为可以提升刷怪塔效率（） 还不用我自己插火把（x",
  "问API去，ATRI没法跟你解释",
  "你先改个环境变量把LANG换成en（ 不然方块怎么玩",
  "没用过这包",
  "为什么会先写bridge（",
  "两个星期的话倒也还行",
  "群里有会的吗（",
  "chihuo: *write AI in js*",
  "/ping baiyuanneko",
  "@mikehay 头疼身子疼，到底哪里疼",
  "但是我可爱的sci回家了",
  "但是我可爱的小括号回家了",
  "显卡上长了个主板",
  "爷爷你star的bbg更新了",
  "<sci:大学没作业么（> 有，等ddl催我",
  "不知道能不能偷过来",
  "我下午进去，mzw已经不见了 我就钓鱼了",
  "@sci 你都背四级了还不会五十音？ chihuo都会",
  "@sci 我觉得你会）",
  "lzy的data（",
  "反手拿土豆",
  "有人玩(mc)吗（",
  "要不柏园猫猫跑我NAS上（x",
  "@mikehay 你可以让谷歌“内网”穿透给你访问 从谷歌看来比较近就是内网了（x",
  "@mikehay 你这都快5个T了还不够",
  "@mikehay 肯定有root的，你看/etc/passwd就有了",
  "我等放送结束一起看（",
  "加热chibot至气态 就能上云了",
  "sci：*吃布丁*",
  "可是这和我柏园猫有什么关系呢（x",
  "chibot在大气层",
  "feat: 定时mcscheck（x",
  "在美国玩游戏就偷着乐吧",
  "chihuo拿自己手机缓存作弊是吧",
  "@chihuo 多次结果还是你的不行",
  "什么互相谦让",
  "@666999HC 注册什么",
  "先打个help wanted 没人愿意写我就打个wontfix",
  "你们现有issue都没结掉还馋新feature",
  "没有的话可以用bbg",
  "群足立监督出来发言",
  "@666999HC 恭喜你完成了",
  "@666999HC 那就 get started 吧",
  "@mikehay 其实加钱都能搞定",
  "sci: feat(fxtz): auto play bot"
]